metadata:
  max_duration_hours: 15

itineraries:
  - from: JFK
    to: SFO
    departure_dates: 2025-12-18,2025-12-20
    currency: USD
  - from: SFO
    to: JFK
    departure_dates: 2026-01-01-3
    currency: USD
